### ISSUE TITLE
Tree view mode doesn't also work with relative paths and doesn't show hidden paths

### ISSUE THREAD

**Issue by eblis** [chrisant996/dirx#3]
The new `--tree` view mode is awesome, but has a few issues I think.

First issue is that it doesn't list paths as relative, even if told to.
Second this is that it doesn't list folders starting with `.`.
I'm running the following command: `dirx -b -s --bare-relative --tree --level=3 --utf8 --icons=always` on the `clink-fzf` repo folder and this is what I see:
![image](https://github.com/chrisant996/dirx/assets/540188/75e44ab2-d3a2-433e-8756-a6062155a4fc)

If I remove the `--tree` flag then I see a lot more files (in the folders starting with `.`) and I also see relative paths, not full paths.
![image](https://github.com/chrisant996/dirx/assets/540188/215e42a0-6365-44df-996e-db404da9444c)

**Comment by chrisant996** [comment]
(Also, eza does not list Hidden files and dirs in its `--tree` mode, either.)

**Comment by eblis** [comment]
What lead me to open this issue is the FZF preview window (again 😄)
I was using `eza` for my folder previewing before, as `dirx` didn't have tree mode before `v.0.11` and I decided to switch to `dirx` since you added tree view mode.

I usually use the folder preview mode to quickly glance to see if the folder structure is matching what I expect the folder to look like.
But when I glance at the preview window the first thing I see is something I do not expect, it's not the currently selected folder, it's the parent path to it (I already know this info as I'm in this folder anyway), and then the selected folder name.

And for longer paths the current selected folder name is not visible in the preview window anymore, since the parent path takes the whole width of the preview window (with the `40%` i use by default)

EZA with folder preview. I'm not sure how I can tell it to use absolute paths, from what I can see it always uses relative paths in tree mode.
![image](https://github.com/chrisant996/dirx/assets/540188/c8f4aa02-9b85-4810-bdb7-7c98771c303d)

Dirx with folder preview
![image](https://github.com/chrisant996/dirx/assets/540188/af6cdb6a-0d96-4952-9336-8fc4d8b923a5)

> DirX is permissive about mutually exclusive flags, and ignores nonsensical ones.
 Would you prefer for it to aggressively give errors about conflicting flags?
 That would require turning off various flags before being able to specify new flags.
 It seems like that would produce a very poor experience, and be highly inconvenient.

I agree, it should allow mutually exclude flags, it would be a pain to run it with the correct flags otherwise.

**Comment by chrisant996** [comment]
Got it, thanks.  The scenario makes sense.  Give me a day or two to think about it.  I'm not convinced that "bare relative" is a reasonable name, if the behavior will expand in this way.

**Comment by chrisant996** [comment]
`--bare-relative` was updated to work with `--tree`.
