### ISSUE TITLE
--hide-dot-files is not hidding dot files

### ISSUE THREAD

**Issue by AngelAGBL** [chrisant996/dirx#5]
I want to hide the dot files in my home directory but this isn't working like expected, here is an screenshot:
![imagen](https://github.com/chrisant996/dirx/assets/106941728/a3e317c4-0085-4437-ad84-29d792df9286)

**Comment by chrisant996** [comment]
Thanks for reporting this.

It got broken by a refactor in cb16e60f3302ad77f7450e22deaf15c8e82f1906 on 2/19.

**Comment by chrisant996** [comment]
v0.15 was published with the fix.

If you're aiming for defaults similar to `ls` then you might also be happy with `--nix` (or even prefer it) which implies hiding dot files, among other things.
